const express = require('express')
const app = express()
app.use('/rubiks-cube-solution', express.static('dist'))
app.listen(8080)
const op = require('open')
op('http://127.0.0.1:8080/rubiks-cube-solution')